### ISSUE TITLE
Python version < 3 needed

### ISSUE THREAD

**Issue by tilmanbeck** [rmit-ir/SummaryRank#1]
Hey guys, I tried to run the code using `python3.5`. Unfortunately, I got some print-related compile-errors and the KrovetzStemmer requirement couldn't be installed. May be you could add the python version, which was used under development.
Greetings

**Comment by rueycheng** [comment]
Hi, thanks for the feedback.  The thing is, none of us is particularly familiar with code transition from python 2.7 to 3.5.  If the errors are just the print function then I could do something about it.  Can you elaborate please?

Regarding the problem with KrovetzStemmer, we need you to open a new issue at the KrovetzStemmer repo, perhaps with some more details about the errors you got.

Cheers

**Comment by rueycheng** [comment]
I'm gonna close this issue as I saw no progress in discussing the problem over the past 4 months.
