### ISSUE TITLE
Index (WPAdatset and Wikipedia)

### ISSUE THREAD

**Issue by rambo07** [rmit-ir/SummaryRank#2]
Hi,
Thanks for the nice repo and proper guideline and documentation.
I am trying to replicate and extend the system. Can you provide more information regarding the manner you created the index for the WPA-DATASET (Gov2) and Wikipedia for ESA.

How flexible is it to merge lucene index instead of Galago or Indri?

**Comment by rueycheng** [comment]
Hi,

You are more than welcome to replicate our results!  For that experiment, we built two Galago indexes, one over the entire GOV2 collection and the other over the English Wikipedia dump (on May 15, 2015, to be specific).  For the build params we probably just specified --stemmer and that's it.  The exact line for both corpora should be something like this:

    galago --indexPath=/path/to/index --inputPath+/path/to/trectext --stemmer+krovetz --stemmer+porter

We probably used some other Tupleflow Flags but this doesn't really matter. 

For using Lucene I think it's doable, but you need to roll your own index class and also change the lines that had the class name `GalagoIndex` hard-coded.  The glue code for talking to indexing tools is basically in `summaryrank/resources.py`.  Have a look and see that helps.

Cheers

**Comment by rambo07** [comment]
Thanks, I finally manged to get Indri engine working.

Best Regards,
Piyush
