### ISSUE TITLE
Galago Index Requirement

### ISSUE THREAD

**Issue by SophyXu** [rmit-ir/SummaryRank#3]
Hi! I try to run the code to generate LanguageModelScore and BM25Score features. But I am quite confused about how to build Galago inverted index path. Is there any instruction?

Thank you so much!

**Comment by rueycheng** [comment]
Hi Sophy, 

You need to have a background model for the purpose of smoothing (as with LM) and estimating document frequency (as with BM25).  We basically used two Galago indexes in the paper, one over Gov2 as the background model and the other over English Wikipedia for computing ESA, both built with this simple line:

    galago --indexPath=/path/to/index --inputPath+/path/to/trectext --stemmer+krovetz --stemmer+porter

Cheers

**Comment by nstfk** [comment]
Hi!!
Well I am also trying to build the Galago index so I can eventually compute the BM25 similarity but even with your prior post I am confused on how to ?
So should I download the galalo and build it separably or do I run the above command from SummaryRank.
Thanks

**Comment by rueycheng** [comment]
You need to download Galago separately and use it to build the required indexes.  Once you have galago installed somewhere, follow my example with 'galago' command replaced by the actual galago executable. This should work out of the box.

**Comment by nstfk** [comment]
Great .. worked like a charm !!
Thank you for the quick response!
